feat: add item-request, tests
VasilisaKo/java-shareit pull request #3
Opened 2023-06-22 16:28 UTC by VasilisaKo

2023-06-23 23:45 UTC, AnastasiyaFomkina requested changes

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +@Validated
Здесь нужно вернуть `@Transactional` и нужно убрать `@Validated`, так как он лиший, валидация должна быть на уровне контроллера и dto-полей. А вот [здесь](https://medium.com/@kirill.sereda/%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%B2-spring-framework-a7ec509df6d2) можно подробнее почитать про транзакции

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
>          switch (state) {
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
>  @Data
_Саморазвитие_
Лучше не использовать `@Data`, так как она несет за собой много скрытых проблем. Вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +}*/
Неиспользуемый код нужно удалять, если он вдруг понадобиться, его всегда можно будет восстановить из истории гита

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  @Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)
Нужно удалить `@Data` из jpa-сущностей по всему проекту

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +    LocalDateTime end;
Нужно добавить модификатор доступа полям 52-53

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +    private User owner;
Поля 46-47 лучше перенести внутрь метода `setUp`, так как они используются только в нем

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +    public static final String USER_ID_HEADER = "X-Sharer-User-Id";
Нужно вынести в отдельный класс, сделать публичной константой и переиспользовать по всему проекту, а не дублировать в каждом классе.
Чтобы быстро заменить значения можно воспользоваться сочетанием клавиш [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html?keymap=primary_windows#replace_search_string_in_project)

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +    public void setUp() throws Exception {
Метод не выбрасывает ошибок
```suggestion
    public void setUp() {
```

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/CommentControllerTest.java
> +    LocalDateTime end;
Нужно добавить модификаторы доступа

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/CommentControllerTest.java
> +    public void setUp() throws Exception {
Нужно удалить лишний throws

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/ItemControllerTest.java
> +    private User booker;
Не используется

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/CommentControllerTest.java
> +    private User owner;
Нужно убрать в метод setUp

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/ItemControllerTest.java
> +    private Item item;
Нужно убрать в метод setUp

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/CommentControllerTest.java
> +        Integer bookerId = 2;
Не используется

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/ItemControllerTest.java
> +    public void setUp() throws Exception {
Лишний throws

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +    private User userTwo;
Поля 38-39 не используются

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/controller/UserControllerTest.java
> +    UserDto userDto = new UserDto(1, "user", "user@user.com");
У полей не хватает модификаторов доступа

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/jpa/BookingDataJpaTest.java
> +        LocalDateTime time = LocalDateTime.now().withNano(000000);
Не используется

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/jpa/BookingDataJpaTest.java
> +    void testBookingDto() throws Exception {
Убери, пожалуйста, лишние throws во всех тестах

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/jpa/CommentDataJpaTest.java
> +        LocalDateTime time = LocalDateTime.now().withNano(000000);
Будет работать и с простым 0
```suggestion
        LocalDateTime time = LocalDateTime.now().withNano(0);
```

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +import javax.persistence.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/service/BookingServiceMokTest.java
> +    private BookingResponseDto bookingResponseDto;
Нужно:
*  удалить лишние и неиспользуемые переменные во всех тестах
*  убрать из переменных класса в переменные метода те, что используются только внутри одного метода
*  убедиться, что для всех переменных класса проставлены модификаторы доступа
*  удалить лишние throws 

во всех тестах

2023-06-23 23:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/service/BookingServiceMokTest.java
> +        bookingList.add(booking);
Код со строк 119-121 повторяется ниже. Во всех тестах нужно выделить общие части кода в отдельные приватные методы или `@BeforeEach`, а не дублировать их

2023-06-24 23:16 UTC, VasilisaKo commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +import javax.persistence.*;
Отдельное спасибо за все статьи

2023-06-24 23:31 UTC, VasilisaKo commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +    private User owner;
booker используется на 88 строке

2023-06-25 00:30 UTC, VasilisaKo commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
>          switch (state) {
Отдельное спасибо за задание со звездочкой. В связи с надвигающимся жестким дедлайном. пока пропущу, но постараюсь вернутся, как только позволит время

2023-06-26 13:29 UTC, afomkina approved these changes
Клево, что проработала все комментарии, молодец 👍

2023-06-29 13:14 UTC, merged